# Generated by Django 4.2.30 on 2026-04-17 01:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('inn', models.CharField(max_length=10)),
                ('legal_address', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_fio', models.CharField(max_length=100)),
                ('passport_series', models.CharField(max_length=4)),
                ('passport_number', models.CharField(max_length=6)),
                ('address', models.CharField(max_length=300)),
                ('start_date', models.DateField()),
                ('compane_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.companies')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_app.position')),
            ],
        ),
    ]
