# Generated by Django 4.2.30 on 2026-04-17 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_app', '0002_alter_companies_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
